### ISSUE TITLE
publish on pypi.python.org

### ISSUE THREAD

**Issue by berendt** [matveyco/cex.io-api-python#5]
Can you please publish your library on pypi.python.org?

**Comment by craigatron** [comment]
+1, this would be nice

**Comment by llazzaro** [comment]
right now after my merge you can install this with
pip install https://github.com/matveyco/cex.io-api-python.git

the author of the project need to follow this steps in order to publish it to pypi
http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by berendt** [comment]
Cleaning up my open issues, I will close this issue, looks like the project is not longer active.
